[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/Michael20070814"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://x.com/Qingmeng0814"

    [social.params]
        icon = "brand-twitter"
